---
#
# Playbook to install the ELK stack + Beats
#
- hosts: k8s_master
  remote_user: ubuntu
  become: yes
  become_user: root
  roles:
  - { role: EL/java }
  - { role: EL/elasticsearch }
  - { role: EL/kibana }
  - { role: EL/metricbeat }

